FROM ncf-base 

RUN \ 
      apt-get update && \
      DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
      git \
      cmake \
      build-essential \
      wget \
      zlib1g-dev \
      libpcre2-dev \
      pkg-config \
      libavl-dev \
      libev-dev \
      libprotobuf-c-dev \
      protobuf-c-compiler \
      libssl-dev \
      swig \
      python-dev \
      # for tsn-demo
      libxml2-dev \ 
      libnl-genl-3-dev \
      libnl-route-3-dev \
      libnl-nf-3-dev \
      libcjson-dev \
      lldpd \
      libdbus-1-dev \
      libhiredis-dev \
      gdb
      
# use /opt/dev as working directory
RUN mkdir /opt/dev
WORKDIR /opt/dev

#RUN \
#    git clone http://git.libssh.org/projects/libssh.git && \
#    cd libssh && \
#    git checkout libssh-0.9.6 && \
#    mkdir build && \
#    cd build && \
#    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr  .. && \
#    make install && \
#    ldconfig && \
#    rm -rf /opt/dev/libssh
    
# install pre-built packages
COPY libssh0.9.6/ /

COPY deb-ub-20 /deb-ub-20
RUN \
    cd /deb-ub-20 && \
    dpkg -i libyang2_2.0.164-1_amd64.deb \
            libyang2-dev_2.0.164-1_amd64.deb \
            libnetconf2-3_2.1.7-1_amd64.deb \
            libnetconf2-dev_2.1.7-1_amd64.deb \
            libsysrepo7_2.1.42-1_amd64.deb \
            libsysrepo-dev_2.1.42-1_amd64.deb \
            sysrepo-tools_2.1.42-1_amd64.deb \
            netopeer2_2.1.16-1_amd64.deb  && \
    cd / && \
    rm -rf /deb-ub-20

# install needed yang files
COPY tsn-mod /tsn-mod
RUN \
    cd /tsn-mod && \
    sysrepoctl -i iana-if-type\@2017-01-19.yang && \
    sysrepoctl -i ieee802-dot1ab-lldp.yang -s . && \
    sysrepoctl -i ietf-hardware\@2018-03-13.yang -s . && \
    sysrepoctl -i iana-hardware\@2018-03-13.yang -s . && \
    cd / && \
    rm -rf /tsn-mod




# libyang
#RUN \
#      cd /opt/dev && \
#      git clone -b master https://github.com/CESNET/libyang.git 
#&& \
#      cd libyang && mkdir build && cd build && \
#      cmake -DCMAKE_BUILD_TYPE:String="Debug" -DENABLE_BUILD_TESTS=OFF .. && \
#      make -j2 && \
#      make install && \
#      ldconfig

# sysrepo
#RUN \
#      cd /opt/dev && \
#      git clone -b master https://github.com/sysrepo/sysrepo.git
# && \
#      cd sysrepo && mkdir build && cd build && \
#      cmake -DCMAKE_BUILD_TYPE:String="Debug" -DENABLE_TESTS=OFF -DREPOSITORY_LOC:PATH=/etc/sysrepo .. && \
#      make -j2 && \
#      make install && \
#      ldconfig

# libnetconf2
#RUN \
#      cd /opt/dev && \
#      git clone -b master https://github.com/CESNET/libnetconf2.git 
#&& \
#      cd libnetconf2 && mkdir build && cd build && \
#      cmake -DCMAKE_BUILD_TYPE:String="Debug" -DENABLE_BUILD_TESTS=OFF .. && \
#      make -j2 && \
#      make install && \
#      ldconfig

# keystore
#RUN \
#      cd /opt/dev && \
#      git clone -b master https://github.com/CESNET/Netopeer2.git 
#&& \
#      cd Netopeer2 && \
#      mkdir build && cd build && \
#      cmake -DCMAKE_BUILD_TYPE:String="Debug" .. && \
#      make -j2 && \
#      make install && \
#      ldconfig

# netopeer2
#RUN \
#      cd /opt/dev && \
#      cd Netopeer2/server && mkdir build && cd build && \
#      cmake -DCMAKE_BUILD_TYPE:String="Debug" .. && \
#      make -j2 && \
#      make install && \
#      cd ../../cli && mkdir build && cd build && \
#      cmake -DCMAKE_BUILD_TYPE:String="Debug" .. && \
#      make -j2 && \
#      make install

ENV EDITOR vim
EXPOSE 830

COPY deb-ub-20/supervisord.conf /etc/supervisord.conf
CMD  ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
